### ISSUE TITLE
Nested Folder Collections

### ISSUE THREAD

**Issue by HaoZeke** [lowmess/metalsmith-auto-collections#2]
For nested folders I notice that the present behavior sets the full path, ie. given

- Articles
--------------- Test

I get the files in Test to be of collection Articles/Test

Is this the expected behavior? The docs mention getting the parent directory, so maybe it ought to return Test?

**Comment by lowmess** [comment]
should be fixed in `v0.1.3` :)

**Comment by HaoZeke** [comment]
Yup, working perfectly.. Thanks!

**Comment by lowmess** [comment]
No problem!

**Comment by HaoZeke** [comment]
Actually I realize it might make more sense to have this as it allows for nested TOC layouts....

Maybe a revert and a slight change in the readme?

(sorry)

**Comment by lowmess** [comment]
I think it's best to keep the collection name how it is now, but I can add a `parent` key to the file metadata with the full path.

**Comment by HaoZeke** [comment]
Yup, that'd be even better 👍

**Comment by lowmess** [comment]
@HaoZeke would you prefer the source file be included or not? in your example, should it be `/source/articles/test` or just `/articles/test`? i can see pros and cons to both sides, so i'll leave it up to the feature-requester ;)

**Comment by lowmess** [comment]
the way I have it now is like this:

| `file.collection` | `file.parent` |
|:---|:---|
| `test` | `/source/posts/test` |

let me know if that works for you and i'll publish the package next time i'm at my desk.

however, the more i think about this, the more i'm sure there's a much better way to achieve automatic, nested navigation. ¯\\\_(ツ)\_/¯

**Comment by HaoZeke** [comment]
Sorry it took so long to get back to you on this...

I do believe having source would be more useful.

I'm sort of at my wits end about automatic nested navs TBH.

**Comment by lowmess** [comment]
No worries, the `parent` key was added in `0.1.4`
